name: 打包 waterRPA 成 exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: waterRPA  # 关键：进入子文件夹
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: 打包 exe
        run: |
          pyinstaller -w -F --icon="logo.ico" --add-data "ui;ui" --add-data "resource;resource" Water.py

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: waterRPA-exe
          path: waterRPA/dist/Water.exe
